version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db/mydatabase
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data:
